'''
Created on Jan 26, 2013

@author: Reza

'''
import pygame
pygame.init()

global WINDOWWIDTH
WINDOWWIDTH = 1280

global WINDOWHEIGHT
WINDOWHEIGHT = 720

global DOORWIDTH
DOORWIDTH = 50

global DOORHEIGHT
DOORHEIGHT = 150

global NUMDOORFRAMESCLOSED
NUMDOORFRAMESCLOSED = 1

global NUMDOORFRAMESOPENED
NUMDOORFRAMESOPENED = 1

global NUMLOCKFRAMESLOCKED
NUMLOCKFRAMESLOCKED = 1

global NUMLOCKFRAMESUNLOCKED
NUMLOCKFRAMESUNLOCKED = 1

global LOCKWIDTH
LOCKWIDTH = 20

global LOCKHEIGHT
LOCKHEIGHT = 20

global ROOMWIDTH
ROOMWIDTH = 1280

global ROOMHEIGHT
ROOMHEIGHT = 720

global NUMROOMFRAMES
NUMROOMFRAMES = 1

global MAXGRAV
MAXGRAV = 20

global CHARWIDTH
CHARWIDTH = 75

global CHARHEIGHT
CHARHEIGHT = 125

global NUMCHARIDLEFRAMES
NUMCHARIDLEFRAMES = 4

global NUMCHARMOVINGHFRAMES
NUMCHARMOVINGHFRAMES = 6

global NUMCHARATTACKINGFRAMES
NUMCHARATTACKINGFRAMES = 3

global CHARATTACKHEIGHT
CHARATTACKHEIGHT = 125

global CHARATTACKWIDTH
CHARATTACKWIDTH = 150

global MOVEMENT
MOVEMENT = 5

global PLAYERIDLESPRITE_FN
PLAYERIDLESPRITE_FN = "Images\CharIdle.png"

global  PLAYERIDLESPRITE
PLAYERIDLESPRITE = pygame.image.load(PLAYERIDLESPRITE_FN)

global PLAYERWALKSPRITE_FN
PLAYERWALKSPRITE_FN = "Images\CharWalking.png"

global PLAYERWALKSPRITE
PLAYERWALKSPRITE = pygame.image.load(PLAYERWALKSPRITE_FN)

global PLAYERATTACKSPRITE_FN
PLAYERATTACKSPRITE_FN = "Images\CharAttacking.png"

global PLAYERATTACKSPRITE
PLAYERATTACKSPRITE = pygame.image.load(PLAYERATTACKSPRITE_FN)

global PLAYERJUMPTIME
PLAYERJUMPTIME = 2

global PLAYERHURTBOXWIDTH
PLAYERHURTBOXWIDTH = 50

global PLAYERHURTBOXHEIGHT
PLAYERHURTBOXHEIGHT = 125

global PLAYERHURTBOXADJUSTMENT
PLAYERHURTBOXADJUSTMENT = 50

global LEFT
LEFT = 'left'

global RIGHT
RIGHT = 'right'

global BACKGROUNDLOCATION
BACKGROUNDLOCATION = (0,0)

global ROOM1_FN
ROOM1_FN = "Images\Room1.png"

global ROOM2_FN
ROOM2_FN = "Images\Room2.png"

global ROOM3_FN
ROOM3_FN = "Images\Room3.png"

global DOOR_FN
DOOR_FN = "Images\door.png"

global DOORIMG
DOORIMG = pygame.image.load(DOOR_FN)

global ENEMYHEIGHT
ENEMYHEIGHT = 100

global ENEMYWIDTH
ENEMYWIDTH = 50

global SEEKDISTANCE
SEEKDISTANCE = 300

global ENEMYPATROLSPEED
ENEMYPATROLSPEED = 1

global ENEMYSEEKSPEED
ENEMYSEEKSPEED = 3

global ENEMYWALKSPRITESHEET_FN
ENEMYWALKSPRITESHEET_FN = "Images\ArmLimbEnemyWalk.png"

global ENEMYWALKSPRITESHEET
ENEMYWALKSPRITESHEET = pygame.image.load(ENEMYWALKSPRITESHEET_FN)

global ENEMYMOVINGFRAMES
ENEMYMOVINGFRAMES = 4

global WAITIME
WAITTIME = 60

global KNOCKBACKDISTANCE
KNOCKBACKDISTANCE = 10

global HEARTHFULL_FN
HEARTFULL_FN = "Images\HeartFull.png"

global HEARTFULL
HEARTFULL = pygame.image.load(HEARTFULL_FN)

global HEARTONEHIT_FN
HEARTONEHIT_FN = "Images\HeartOneHit.png"

global HEARTONEHIT
HEARTONEHIT = pygame.image.load(HEARTONEHIT_FN)

global HEARTTWOHITS_FN
HEARTTWOHITS_FN = "Images\HeartTwoHits.png"

global HEARTTWOHITS
HEARTTWOHITS = pygame.image.load(HEARTTWOHITS_FN)

global HEARTTHREEHIT_FN
HEARTTHREEHITS_FN = "Images\HeartThreeHits.png"

global HEARTTHREEHITS
HEARTTHREEHITS = pygame.image.load(HEARTTHREEHITS_FN)

global HEARTEMPTY_FN
HEARTEMPTY_FN = "Images\HeartEmpty.png"

global HEARTHEMPTY
HEARTEMPTY = pygame.image.load(HEARTEMPTY_FN)

global HEARTWIDTH
HEARTWIDTH = 200

global HEARTHEIGHT
HEARTHEIGHT = 80

global HEARTFRAME
HEARTFRAME = 1

global TITLESCREEN_FN
TITLESCREEN_FN = "Images\TitleScreen.png"

global TITLESCREEN
TITLESCREEN = pygame.image.load(TITLESCREEN_FN)

global GAMEOVER_FN
GAMEOVER_FN = "Images\GameOverScreen.png"

global GAMEOVERSCREEN
GAMEOVERSCREEN = pygame.image.load(GAMEOVER_FN)

global TITLE
TITLE = "title"

global PLAYING
PLAYING = "playing"

global GAMEOVER
GAMEOVER = "gameover"

global BGMUSIC_FN
BGMUSIC_FN = "SOund\Cypher.ogg"
